App\Catalogue\Entity\Product:
  properties:
    name:
      - NotBlank: ~
    priceValue:
      - NotBlank: ~
    priceCurrency:
      - NotBlank: ~

App\Cart\Infrastructure\DTO\AddProductToCartPayload:
  properties:
    productId:
      - NotBlank: ~
