parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $userId: '%app.user_id%'

  _instanceof:
    App\Cart\Infrastructure\Messenger\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    App\Cart\Infrastructure\Messenger\QueryHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: query.bus }

  App\Cart\:
    resource: '../'

  App\Cart\UI\Api\:
    resource: '../UI/Api/'
    tags: ['controller.service_arguments']

  App\Cart\Domain\CartRepositoryInterface:
    class: App\Cart\Infrastructure\Persistence\CartRepository
